ADT_booking/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users.views import register_patient
from bookings.views import redirect_to_home

urlpatterns = [
    path('', redirect_to_home, name='redirect-to-home'),
    path('adtbooking/', include('bookings.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('users/register-patient/', register_patient, name='register-patient'),
    path('users/', include('users.urls')),
    path('payment/', include('payments.urls'))
]


urlpatterns += staticfiles_urlpatterns()

admin.site.site_header = "ADT Booking Admin"
admin.site.site_title = "ADT Admin Site"
admin.site.index_title = "Welcome to ADT Booking System"

bookings/urls.py
from django.urls import path
from . import views

app_name = 'bookings'

urlpatterns = [
    path('session/view/all', views.SessionListView.as_view(), name='view_session_all'),
    path('session/new/1', views.CreateSessionStep1View.as_view(), name='new_session1'),
    path('session/new/2', views.CreateSessionStep2View.as_view(), name='new_session2'),
    path('session/new/3', views.CreateSessionStep3View.as_view(), name='new_session3'),
    path('session/new/claim-payment',
         views.CreateSessionClaimConservativePaymentView.as_view(),
         name='new_session_claim_conservative_payment'),
    path('session/new/3b', views.CreateSessionStep3bView.as_view(), name='new_session3b'),
    path('update-session-home/', views.session_update_home, name='session_update_home'),
    path('update-session/<int:pk>/', views.PatientSessionListView.as_view(), name='update_session'),
    path('session/<int:pk>/', views.SessionDetailView.as_view(), name='session-detail'),
    path('session/edit/<int:pk>/', views.SessionUpdate.as_view(), name='session-edit'),
    path('', views.home, name='bookings-home')
]

payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    path('view/all', views.PaymentsListView.as_view(), name='view_payment_all'),
    path('new/choose', views.choose_payment_to_post, name='choose_payment_to_post'),
    path('new/<str:choice>', views.create_payment, name='create_payment'),
    path('update-payment-home/', views.payment_update_home, name='payment_update_home'),
    path('update-payment/<int:pk>/', views.PatientPaymentListView.as_view(), name='update_payment'),
    path('payment/edit/<int:pk>/', views.PaymentUpdateView.as_view(), name='payment-edit'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('view-patients/', views.PatientsListView.as_view(), name='view_patients'),
    path('update-patient-home/', views.patient_update_home, name='patient_update_home'),
    path('update-patient/<int:pk>/', views.PatientUpdateView.as_view(), name='update_patient'),
    path('search-patient/home/', views.search_patient_home, name='search_patient_home'),
    path('search-patient/<str:q>/', views.SearchPatients.as_view(), name='search_patient'),
    path('patient-autocomplete', views.PatientAutocompleteView.as_view(), name='patient_autocomplete'),
    path('patient/<int:pk>', views.PatientDetailView.as_view(), name='patient-detail'),
    path('reports/home', views.reports_home, name='reports_home'),
    path('reports/bookings/list', views.booking_listing_report, name='booking_listing_report'),
    path('reports/patients/list', views.patient_listing_report, name='patient_listing_report'),
    path('reports/payments/list', views.payment_listing_report, name='payment_listing_report')
]

bookings/views.py
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.views.generic import ListView, DetailView, UpdateView
from django.utils.dateparse import parse_date

from django.urls import reverse_lazy
from .models import (
    Session,
    Service,
    SessionStatus,
    DEFAULT_SESSION_STATUS_ID
)
from payments.models import (
    CorporatePayment,
    Payment,
    CashPayment,
    UndefinedPaymentMethod,
    InsurancePayment,
    InsuranceCompany,
    MobileBankingPayment,
    MobileBankingType,
)
from users.models import Patient, Doctor
from payments.searches import get_conservative_unclaimed_payments
from payments.forms import (
    CashOrUndefinedPaymentForm,
    InsurancePaymentForm,
    MobilePaymentForm,
    CorporatePaymentForm
)
from .forms import (
    NewSessionStep1Form,
    NewSessionStep2Form,
    NewSessionStep3NewPaymentForm,
    SessionUpdateModelForm
)

SESSION_DETAIL_URL = 'session/'

# Create your views here.
def redirect_to_home(request):
    return redirect('bookings:bookings-home')


@login_required
def home(request):
    if request.user.is_staff:
        messages.info(
            request,
            "Kindly, navigate to the Admin page to utilize all your rights"
        )
    context = {
        'title': 'Home'
    }
    return render(request,'bookings/bookings_home.html', context)


class CreateSessionStep1View(LoginRequiredMixin, View):

    form_class = NewSessionStep1Form
    template_name = "bookings/bookings_home.html"
    context = {
        'title': 'Book Patient',
        'heading': 'search patient'
    }

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        self.context['form1'] = form
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            request.session['patient_pk'] = form.cleaned_data['patient'].pk
            return redirect('bookings:new_session2')
        self.context['form1'] = form
        return render(request, self.template_name, self.context)


class CreateSessionStep2View(LoginRequiredMixin, View):

    form_class = NewSessionStep2Form
    template_name = "bookings/bookings_home.html"
    context = {
        'title': 'Book Patient',
    }

    def get(self, request, *args, **kwargs):
        form = self.form_class()

        """filling non-editable info into form 1"""
        patient = Patient.objects.filter(pk=request.session.get('patient_pk')).first()
        print(request.session.items())
        form1 = NewSessionStep1Form(initial={
            'patient': patient
        })
        """disabling form1"""
        for key in form1.fields.keys():
            form1.fields[key].disabled = True
        """end of disabling form1"""
        """End of form1 info"""

        self.context['form1'] = form1
        self.context['form2'] = form

        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        request.session['form2'] = {}
        if form.is_valid():

            for key, value in form.cleaned_data.items():
                if key in ('start_date', 'end_date'):
                    request.session["form2"][key] = str(value)
                elif key in ('service', 'doctor', 'location', 'bed_type', 'booking_type'):
                    request.session["form2"][key] = value.pk
                else:
                    request.session["form2"][key] = value

            print("Form: ", form.cleaned_data.items())
            print("session: ", request.session.items())
            if request.session["form2"].get('payment_choice', None) == '2':
                return redirect('bookings:new_session_claim_conservative_payment')
            else:
                return redirect('bookings:new_session3')

        self.context['form2'] = form
        return render(request, self.template_name, self.context)


class CreateSessionClaimConservativePaymentView(LoginRequiredMixin, View):
    template_name = 'bookings/conservative_unclaimed_payment_form.html'
    context = {
        'title': 'Payment Detail',
        'heading': 'Unclaimed Payments'
    }

    def get(self, request, *args, **kwargs):

        """checks if the user had chosen 'Claim posted payment'"""

        try:
            if request.session.get('form2', None).get('payment_choice', None) == '2':
                """if True, the user is redirected to CreateSessionStep3bView"""

                pass
            else:
                return redirect('bookings:new_session3')
        except AttributeError:
            return redirect('bookings:new_session1')
        """end"""

        patient_pk = request.session.get('patient_pk', None)
        patient = Patient.objects.filter(pk=patient_pk).first()
        payments = get_conservative_unclaimed_payments(patient_pk).order_by('-date')
        self.context['conservative_unclaimed_payments'] = payments
        self.context['patient'] = patient
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        payment = request.POST.get('payment_id', None)

        """debug prints"""
        print(request.POST.get('payment_id', None))
        print(payment)
        """end of debug prints"""

        if request.POST.get('payment_id', None) is None:
            return redirect('bookings:new_session_claim_conservative_payment')

        payment = Payment.objects.get(pk=int(payment))

        if payment.patient.id != request.session.get('patient_pk', None):
            return redirect('bookings:new_session_claim_conservative_payment')
        else:
            request.session['payment'] = payment.pk
            messages.success(request, "Payment has been successfully set aside for claiming")
        return redirect('bookings:new_session3b')


class CreateSessionStep3View(LoginRequiredMixin, View):
    form_class = NewSessionStep3NewPaymentForm
    template_name = "bookings/bookings_home.html"
    context = {
        'title': 'Book Patient',
    }

    def get(self, request, *args, **kwargs):

        """To fix back button in CreateSessionStep3bView template which redirects here"""
        """checks if the user had chosen 'Claim posted payment'"""

        if request.session["form2"].get('payment_choice', None) == '2':

            """if True, the user is redirected to CreateSessionStep3bView"""

            return redirect('bookings:new_session_claim_conservative_payment')
        """end"""

        form = NewSessionStep3NewPaymentForm
        patient = Patient.objects.filter(pk=request.session.get('patient_pk')).first()
        form1 = NewSessionStep1Form(initial={
            'patient': patient
        })
        """disabling form1"""
        for key in form1.fields.keys():
            form1.fields[key].disabled = True
        """end of disabling form1"""
        """End of form1 info"""
        form2 = NewSessionStep2Form(initial=request.session["form2"])

        for key in form2.fields.keys():
            form2.fields[key].disabled = True

        self.context['form1'] = form1
        self.context['form2'] = form2
        self.context['form3'] = self.form_class

        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        request.session['form3'] = {}
        if form.is_valid():
            for key, value in form.cleaned_data.items():
                if key == 'payment_type':
                    request.session['form3'][key] = value.pk
                else:
                    request.session['form3'][key] = str(value)
            return redirect('bookings:new_session3b')
        self.context['form3'] = form
        return render(request, self.template_name, self.context)


class CreateSessionStep3bView(LoginRequiredMixin, View):
    template_name = "bookings/bookings_home.html"
    form_class = None
    context = {
        'title': 'Book Patient',
    }

    def get(self, request, *args, **kwargs):
        if (request.session['form2']['payment_choice'] == '2'
                or
                request.session['form3']['payment_type'] in (1, 2)):

            self.form_class = CashOrUndefinedPaymentForm
        elif request.session['form3']['payment_type'] == 3:
            self.form_class = InsurancePaymentForm
        elif request.session['form3']['payment_type'] == 5:
            self.form_class = CorporatePaymentForm
        else:
            self.form_class = MobilePaymentForm
        form = self.form_class()
        patient = Patient.objects.filter(pk=request.session.get('patient_pk')).first()
        form1 = NewSessionStep1Form(initial={
            'patient': patient
        })
        """disabling form1"""
        for key in form1.fields.keys():
            form1.fields[key].disabled = True
        """end of disabling form1"""
        """End of form1 info"""
        form2 = NewSessionStep2Form(initial=request.session["form2"])

        for key in form2.fields.keys():
            form2.fields[key].disabled = True

        self.context['form1'] = form1
        self.context['form2'] = form2
        if request.session['form2']['payment_choice'] == '1':
            form3 = NewSessionStep3NewPaymentForm(
                initial=request.session['form3']
            )
            for key in form3.fields.keys():
                form3.fields[key].disabled = True
            self.context['form3'] = form3
        else:
            pass
        self.context['form3b'] = form

bookings/templates/bookings/base2.html
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'bootstrap bundle/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap bundle/jquery.modal.min.css' %}">
    <title>Test</title>
</head>

<body>
    <script src="{% static 'bootstrap bundle/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap bundle/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'bootstrap bundle/jquery.modal.min.js' %}"></script>


    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>

<!-- Create book button -->
<button class="create-pat btn btn-primary" type="button" name="button">Create Book</button>

<script type="text/javascript">
$(document).ready(function() {

    $(".create-pat").modalForm({
        formURL: "{% url 'users:register_patient_modal' %}"
    });

});
</script>

</body>

bookings/templates/bookings/bookings_home.html
{% extends "bookings/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% block content %}
    {% load static %}

    {% if other_form %}
        <div class="row card unset p-2 m-2">
            <div class="col-lg-4 col-md-6 col-sm-8 align-self-center ">
                <form method="post" class="form-main">
                    {% csrf_token %}
                    {{ other_form|crispy }}
                    <div class="submit-row text-center">
                        <input class="btn button" type="submit" value="{% if submit %}{{submit}}{% else %}Edit{% endif %}">
                    </div>
                </form>
            </div>
        </div>
    {% endif %}

    <!--If booking module is active-->

    {% if title == 'Book Patient' %}

            <div class="row mx-auto card">


            <!--step 1-->
                <div class="col">
                    <form class="main-form" method="post">
                        <legend class="text-center font-weight-bold"><span class="number">1</span>Search Patient</legend>
                        {% csrf_token %}
                        {{ form1|crispy }}
                        {% if not form2 %}
                            <div class="submit-row text-center">
                                <input class="btn button" type="submit" value="Next">
                            </div>
                        {% endif %}
                    </form>

                </div>
            <!--en of step 1-->

            <!--step 2-->

                <div class="col">
                    {% if form2%}
                        <form class="main-form" method="post">
                        <legend class="text-center font-weight-bold"><span class="number">2</span>Primary Info</legend>
                        {% csrf_token %}
                        {{ form2|crispy }}
                        {% if not form3%}
                            {% if not form3b %}
                            <div class="submit-row text-center">
                                <a href="{% url 'bookings:new_session1' %}"><span class="btn button">Back</span></a>
                                <input class="btn button" type="submit" value="Next">
                            </div>
                            {% endif %}
                         {% endif %}
                    </form>
                    {% endif %}
                </div>

            <!--end of step 2-->

            <!--step 3-->

                <div class="col">
                    {% if form3 %}
                        <form class="main-form" method="post">
                            <legend class="text-center font-weight-bold"><span class="number">3a</span>Payment Info</legend>
                        {% csrf_token %}
                        {{ form3|crispy }}
                        {% if not form3b %}
                        <div class="submit-row text-center">
                            <a href="{% url 'bookings:new_session2' %}"><span class="btn button">Back</span></a>
                            <input class="btn button" type="submit" value="Next">
                        </div>
                        {% endif %}
                    </form>
                     {% endif %}


                    {% if form3b %}
                    <form class="main-form" method="post">
                        {% csrf_token %}
                        <legend class="text-center font-weight-bold"><span class="number">3b</span>Confirm & Book Patient</legend>
                        {{ form3b|crispy }}
                        <div class="submit-row text-center">
                            <a href="{% url 'bookings:new_session3' %}"><span class="btn button">Back</span></a>
                            <input class="btn button" type="submit" value="Confirm & Book">
                        </div>
                    </form>
                    {% endif %}

                </div>
            <!--end of step 3-->

            </div>



    {% endif %}







    <div class="row text-center mx-auto">

        <!--Registration-->
        <div class="card main mb-2 p-2 mx-auto col-xl-3 col-lg-4 col-md-5 col-sm-6">
            <h1 class="card-header">Patients</h1>
            {% if title == 'Home' %}
                <img src="{% static 'users/logo_and_icons/icons/solid/user-circle.svg' %}" class="card-img icon-lg" alt="patients">
            {% endif %}
            <div class="card-body">
                <a href="{% url 'register-patient' %}" target="_blank"
                            onclick="window.open('{% url 'register-patient' %}',
                                'newwindow',
                                'width=700,height=700');
                                    return false;">
                    <button class="pat-reg btn btn-outline-success submit-btn" type="button" name="button" data-toggle="tooltip" data-placement="bottom" title="Add Patient">
                        <img src="{% static 'users/logo_and_icons/icons/solid/user-plus.svg' %}" class="icon" alt="Add Patient">
                    </button>
                </a>

                {% if user.is_staff %}
                    <a href="{% url 'users:patient_update_home' %}">
                        <span class="btn btn-outline-danger" data-toggle="tooltip" data-placement="bottom" title="Edit Patient">
                            <img src="{% static 'users/logo_and_icons/icons/solid/user-edit.svg' %}" class="icon" alt="edit">
                        </span>
                    </a>
                {% endif %}
                <a href="{% url 'users:view_patients' %}">
                    <button class="btn btn-outline-info" data-toggle="tooltip" data-placement="bottom" title="View Patients">
                        <img src="{% static 'users/logo_and_icons/icons/solid/user-friends.svg' %}" class="icon" alt="view">
                    </button>
                </a>
            </div>
        </div>
        <!--End of Registration-->
        
        <!--Booking-->
        <div class="card main mb-2 p-2 mx-auto col-xl-3 col-lg-3 col-md-4 col-sm-6">
            <h1 class="card-header">Bookings</h1>
            {% if title == 'Home' %}
                <img src="{% static 'users/logo_and_icons/icons/solid/bookmark.svg' %}" class="card-img icon-lg" alt="Bookings">
            {% endif %}
            <div class="card-body">
                <a href="{% url 'bookings:new_session1' %}">
                    <button class="btn btn-outline-success" data-toggle="tooltip" data-placement="bottom" title="Book Patient">
				        <!--img src="{% static 'users/logo_and_icons/icons/solid/user-clock.svg' %}" class="icon"-->New
			        </button>
                </a>
                <a href="{% url 'bookings:session_update_home' %}">
                    <span class="btn btn-outline-danger" data-toggle="tooltip" data-placement="bottom" title="Edit Booking">
                        <img src="{% static 'users/logo_and_icons/icons/solid/pen.svg' %}" class="icon" alt="Edit">
                    </span>
                </a>
                <a href="{% url 'bookings:view_session_all' %}">
                    <span class="btn btn-outline-info" data-toggle="tooltip" data-placement="bottom" title="View Bookings">
                        <!--img src="{% static 'users/logo_and_icons/icons/solid/eye.svg' %}" class="icon" alt="View"-->View
                    </span>
                </a>
            </div>
        </div>
        <!--End of Booking-->

        <!--div class="w-100 d-none d-md-block"></div-->
        
        <!--Update Booking-->
        <div class="card main mb-2 p-2 mx-auto col-xl-3 col-lg-3 col-md-4 col-sm-6">
            <h1 class="card-header">Payments</h1>
            {% if title == 'Home' %}
                <img src="{% static 'users/logo_and_icons/icons/solid/money-check-alt.svg' %}" class="card-img icon-lg" alt="payments">
            {% endif %}
            <div class="card-body">
                <a href="{% url 'payments:choose_payment_to_post' %}">
                    <span class="btn btn-outline-success" data-toggle="tooltip" data-placement="bottom" title="New Payment">New
                    </span>
                </a>
                {% if user.is_staff %}
                    <a href="{% url 'payments:payment_update_home' %}">
                            <span class="btn btn-outline-danger" data-toggle="tooltip" data-placement="bottom" title="Edit Payment">Edit
                        </span>
                    </a>
                {% endif %}
                <a href="{% url 'payments:view_payment_all' %}">
                    <span class="btn btn-outline-info" data-toggle="tooltip" data-placement="bottom" title="View Payments">View
                    </span>
                </a>
            </div>
        </div>
        <!--End of Updating Booking-->
        
        <!--Reports and Extras-->
        <div class="card main mb-2 p-2 mx-auto col-xl-3 col-lg-3 col-md-4 col-sm-6">
            <h1 class="card-header">Extras</h1>
            {% if title == 'Home' %}
                <img src="{% static 'users/logo_and_icons/icons/solid/box-open.svg' %}" class="card-img icon-lg" alt="payments">
            {% endif %}
            <div class="card-body">
                <a href="#" class="btn btn-outline-info">
                    <span data-toggle="tooltip" data-placement="bottom" data-html="true" title="View/Export reports, Add/View Doctors">More...
                    </span>
                </a>
            </div>
        </div>
        <!--End of Reports and Extras-->
    
    </div>
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

    {{ form1.media }}
    {{ form2.media }}
    {{ form3.media }}
    {{ other_form.media }}

{% endblock %}

bookings/templates/bookings/session_detail.html
{% extends 'bookings/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
    <div class="card align-items-center p-2 mx-auto">
        <a href="{% url 'users:patient-detail' object.patient.pk %}">
            <div class="card-header text-center bg-unset">
            <img class="icon-lg rounded-circle"
        {% if object.patient.gender.id == 3 %}
            src="{% static 'users/logo_and_icons/icons/svg/161-user-3.svg' %}" alt="Female"
        {% elif object.patient.gender.id == 2%}
            src="{% static 'users/logo_and_icons/icons/svg/160-user-2.svg' %}" alt="Male"
        {% else %}
            src="{% static 'users/logo_and_icons/icons/svg/159-user-1.svg' %}" alt="Other"
        {% endif %}
        >
        <h3 id="header2" class="header2-fallback-color">
            {{ object.patient.full_name.title }}({{ object.patient.age }}yrs)
        </h3>
        </div>
        </a>
        <div class="card-body">
            <table class="table text-center">
                <thead class="bg-theme">
                    <tr>
                        <th scope="rowgroup" class="font-weight-bold" colspan="3">
                            <h4>Booking Detail</h4>
                        </th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <b>Service: </b> {{ object.service }}
                    </td>
                    <td>
                        <b>Admission Date: </b>{{ object.start_date|date:"jS-N-Y" }}
                    </td>
                    <td>
                        <b>Status: </b> <span style="color: {{ object.status.indicator }};">{{ object.status }}</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>Booking Type: </b>{{ object.booking_type }}
                    </td>
                    <td><b>Allocated Location: </b>{{ object.location }}</td>
                    <td><b>Bed Type: </b>{{ object.bed_type }}</td>
                </tr>
                <tr>
                    <td>
                        <b>Doctor: </b>{{ object.doctor }}
                    </td>
                    <td><b>Discharged? </b>{{ object.is_past }}</td>
                    <td>
                        <b>{% if object.is_past %}Discharged on{% else %}Expected Discharge Date{% endif %}: </b>{{ object.end_date }}
                    </td>
                </tr>
                <tr class="bg-faded-theme text-center">
                    <td colspan="3"><b>Diagnosis</b></td>
                </tr>
                <tr>
                    <td colspan="3">
                        <textarea cols="50" rows="5" disabled class="bg-unset border-info rounded">{{ object.doctor_diagnosis }}</textarea>
                    </td>
                </tr>
                <tr class="bg-theme text-center">
                    <td colspan="3"><b>Payment Info</b></td>
                </tr>
                <tr>
                    <td>
                        <b>Type: </b>{{ object.payment.get_real_instance.type }}
                    </td>
                    <td>
                        <b>Extra-Tags: </b>{{ object.payment.get_real_instance.additional_info }}
                    </td>
                    <td>
                        <b>Amount: </b>{{ object.payment.denom}} {{ object.payment.amount|intcomma }}{{ object.payment.denom_closer }}
                    </td>
                </tr>
                {% if object.remarks != "" %}
                    <tr class="bg-faded-theme text-center">
                        <td colspan="3"><b>Booking remarks</b></td>
                    </tr>
                    <tr>
                        <td colspan="3">
                            <textarea cols="50" rows="5" disabled class="bg-unset border-info rounded">{{ object.remarks }}</textarea>
                        </td>
                    </tr>
                {% endif %}
                <tr class="bg-faded-theme text-center">
                    <td colspan="3"><b>Session Logs/History</b></td>
                </tr>
                <tr>
                    <td colspan="3">
                        <b>Creation Log: </b>{{ object.history.last.history_user }} -- {{ object.date_added }}
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <b>Last Modified by: </b>{{ object.history.first.history_user }} -- {{ object.last_modified }}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div>
            <span class="button btn">
                <a href="{% url 'bookings:view_session_all' %}">Back</a>
            </span>
            {% if not session.is_past %}
                <span class="btn btn-outline-secondary">
                    <a href="{% url 'bookings:session-edit' object.id %}">Edit</a>
                </span>
            {% endif %}
        </div>
    </div>
{% endblock %}

bookings/templates/bookings/session_form.html
{% extends "users/logs_base.html" %}
{% block content %}
    {% load static %}
    {% load crispy_forms_tags %}
    <h1 id="header2">Edit {{ object.patient }} for {{ object.start_date|date:"jS-N-Y" }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="submit-row text-center">
            <a href="{% url 'bookings:session-detail' object.id %}"><span class="btn btn-outline-info">Cancel</span></a>
            <input class="btn button" type="submit" value="Update">
        </div>
        <div class="d-flex align-items-center">
            <small class="text-muted">Waiting...</small>
        <div class="spinner-grow spinner-border-sm text-secondary ml-auto" role="status" aria-hidden="true"></div>
        </div>
    </form>
{% endblock %}