ADT_booking/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users.views import register_patient
from bookings.views import redirect_to_home

urlpatterns = [
    path('', redirect_to_home, name='redirect-to-home'),
    path('adtbooking/', include('bookings.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('users/register-patient/', register_patient, name='register-patient'),
    path('users/', include('users.urls')),
    path('payment/', include('payments.urls'))
]


urlpatterns += staticfiles_urlpatterns()

admin.site.site_header = "ADT Booking Admin"
admin.site.site_title = "ADT Admin Site"
admin.site.index_title = "Welcome to ADT Booking System"

bookings/urls.py
from django.urls import path
from . import views

app_name = 'bookings'

urlpatterns = [
    path('session/view/all', views.SessionListView.as_view(), name='view_session_all'),
    path('session/new/1', views.CreateSessionStep1View.as_view(), name='new_session1'),
    path('session/new/2', views.CreateSessionStep2View.as_view(), name='new_session2'),
    path('session/new/3', views.CreateSessionStep3View.as_view(), name='new_session3'),
    path('session/new/claim-payment',
         views.CreateSessionClaimConservativePaymentView.as_view(),
         name='new_session_claim_conservative_payment'),
    path('session/new/3b', views.CreateSessionStep3bView.as_view(), name='new_session3b'),
    path('update-session-home/', views.session_update_home, name='session_update_home'),
    path('update-session/<int:pk>/', views.PatientSessionListView.as_view(), name='update_session'),
    path('session/<int:pk>/', views.SessionDetailView.as_view(), name='session-detail'),
    path('session/edit/<int:pk>/', views.SessionUpdate.as_view(), name='session-edit'),
    path('', views.home, name='bookings-home')
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('view-patients/', views.PatientsListView.as_view(), name='view_patients'),
    path('update-patient-home/', views.patient_update_home, name='patient_update_home'),
    path('update-patient/<int:pk>/', views.PatientUpdateView.as_view(), name='update_patient'),
    path('search-patient/home/', views.search_patient_home, name='search_patient_home'),
    path('search-patient/<str:q>/', views.SearchPatients.as_view(), name='search_patient'),
    path('patient-autocomplete', views.PatientAutocompleteView.as_view(), name='patient_autocomplete'),
    path('patient/<int:pk>', views.PatientDetailView.as_view(), name='patient-detail'),
    path('reports/home', views.reports_home, name='reports_home'),
    path('reports/bookings/list', views.booking_listing_report, name='booking_listing_report'),
    path('reports/patients/list', views.patient_listing_report, name='patient_listing_report'),
    path('reports/payments/list', views.payment_listing_report, name='payment_listing_report')
]

bookings/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from simple_history.models import HistoricalRecords

# Create your models here.
DEFAULT_DIAGNOSIS = 'none provided'
DEFAULT_SESSION_STATUS_ID = 2


class Service(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField(max_length=100, default="Service. No further description provided")
    history = HistoricalRecords()

    def __str__(self):
        return self.name


class SessionStatus(models.Model):
    status = models.CharField(max_length=10, editable=False)
    indicator = models.CharField(max_length=10)
    history = HistoricalRecords()

    class Meta:
        verbose_name = "Booking Status"
        verbose_name_plural = 'Booking Statuses'

    def __str__(self):
        return self.status


class BookingType(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Location(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class BedType(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


"""DEFAULT_BED_TYPE = BedType.objects.get(pk=1)
DEFAULT_LOCATION = Location.objects.get(pk=1)
DEFAULT_BOOKING_TYPE = BookingType.objects.get(pk=1)"""


class Session(models.Model):
    patient = models.ForeignKey('users.Patient', on_delete=models.PROTECT)
    service = models.ForeignKey(Service, on_delete=models.PROTECT)
    doctor = models.ForeignKey('users.Doctor', on_delete=models.PROTECT)
    doctor_diagnosis = models.TextField(max_length=300, default=DEFAULT_DIAGNOSIS)
    start_date = models.DateField('Admission Date', default=timezone.now)
    end_date = models.DateField('Discharge Date', default=timezone.now)
    payment = models.OneToOneField('payments.Payment', on_delete=models.PROTECT)
    status = models.ForeignKey(SessionStatus, on_delete=models.PROTECT, default=1)
    location = models.ForeignKey(Location, on_delete=models.PROTECT)
    bed_type = models.ForeignKey(BedType, on_delete=models.PROTECT)
    booking_type = models.ForeignKey(BookingType, on_delete=models.PROTECT)
    remarks = models.TextField(max_length=200, blank=True)
    history = HistoricalRecords()
    date_added = models.DateField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('bookings:session-detail', kwargs={'pk': self.pk})
    @property
    def is_past(self):
        return self.end_date < timezone.now().date()
    """is_past.admin_order_field = 'start_date'
    is_past.boolean = True
    is_past.short_description = 'Patient Discharged?'"""
    @property
    def timeline(self):
        if self.start_date > self.end_date:
            return "INCONSISTENT"
        if self.is_past:
            return "PAST"
        elif self.start_date <= timezone.now().date() <= self.end_date:
            return "ACTIVE"
        elif self.start_date > timezone.now().date() and self.end_date >= timezone.now().date():
            return "FUTURE"
        else:
            return "INCONSISTENT"
    def __str__(self):
        return f"for {self.patient.full_name}, {self.location}"

    class Meta:
        verbose_name = "Booking"
        verbose_name_plural = 'Bookings'


class CancelledSession(models.Model):
    session = models.ForeignKey(Session, on_delete=models.PROTECT)
    reason_for_cancelling = models.TextField(max_length=100)
    history = HistoricalRecords()
    date_added = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Cancelled Booking"
        verbose_name_plural = 'Cancelled Bookings'

users/models.py
from django.db import models
from simple_history.models import HistoricalRecords
from django.conf import settings
from django.utils import timezone
from django.urls import reverse

# Create your models here.

DEFAULT_EMAIL = 'none@none.none'


class Gender(models.Model):
    name = models.CharField(max_length=10, unique=True, editable=False)
    history = HistoricalRecords()

    def __str__(self):
        return self.name

    @property
    def initial(self):
        if self.name == 'Other*':
            return '*'
        return self.name[0].upper()


class Patient(models.Model):
    first_name = models.CharField(max_length=20)
    middle_name = models.CharField(max_length=20, blank=True)
    last_name = models.CharField(max_length=20)
    date_of_birth = models.DateField()
    phone_number = models.CharField(max_length=12, unique=True)
    gender = models.ForeignKey(Gender, on_delete=models.PROTECT, default=3)
    email = models.EmailField(unique=True, null=True, blank=True)
    uhid = models.BigIntegerField(unique=True, blank=True, null=True)
    history = HistoricalRecords()
    date_added = models.DateField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('users:patient-detail', kwargs={'pk': self.pk})

    @property
    def full_name(self):
        if self.middle_name:
            return f'{self.first_name} {self.middle_name} {self.last_name}'
        return f'{self.first_name} {self.last_name}'

    @property
    def age(self):
        today = timezone.now().date()
        age = today.year - self.date_of_birth.year - (
                (today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day)
        )

        return age

    def __str__(self):
        return self.full_name


class Doctor(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=12)
    gender = models.ForeignKey(Gender, on_delete=models.PROTECT)
    email = models.EmailField(default=DEFAULT_EMAIL, null=True)
    history = HistoricalRecords()
    date_added = models.DateField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

users/views.py
# Other imports
from django.db.models import Q
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# end of other imports


# mixins and generic views class imports
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import (
    ListView,
    UpdateView,
    DetailView
)
from bookings.forms import NewSessionStep1Form
# end of generic views and mixins imports

# dal auto-complete imports
from dal import autocomplete
# end of dal auto-complete

# models import
from .models import Patient
# end of model imports

# form imports
from .forms import (
    PatientRegistrationForm,
    PatientReportFilterForm,
    BookingReportFilter,
    PaymentReportFilter
)

# end of form imports

"""end of forms imports"""

from users.models import Patient
from .filters import(
    patient_list_root,
    bookings_list_root,
    payment_list_root
)

# Create your views here.
@login_required
def register_patient(request):
    context = {
        'title': 'New Patient'
    }
    if request.method == 'POST':
        form = PatientRegistrationForm(request.POST)
        context['form'] = form
        if form.is_valid():
            form.save()
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            messages.success(request, f"The patient '{first_name} {last_name}' has been successfully registered")
            success = [f"The patient '{first_name} {last_name}' has been successfully registered", ]

            # pop-up (messages and context)

            msgs = {}
            error = []
            warning = []
            msgs['success'] = [msg for msg in success]
            msgs['danger'] = [msg for msg in error]
            msgs['warning'] = [msg for msg in warning]
            context['msgs'] = msgs
            context['title'] = 'Success! close pop-up'

            # end of pop-up (messages and context)

            return render(request, template_name='users/logs_base.html', context=context)
    else:
        form = PatientRegistrationForm()
        context['form'] = form
    return render(request, 'users/users_register_patient.html', context)


class PatientsListView(LoginRequiredMixin, ListView):
    model = Patient
    template_name = 'users/patients_listview.html'
    context_object_name = 'patients'
    paginate_by = 20
    ordering = ['-last_modified']


def search_patient_home(request):
    if request.method == 'GET':
        q = (request.GET.get('q', None))
        if q == '':
            return redirect('bookings:bookings-home')
        return redirect('users:search_patient', q)
    return redirect('bookings:bookings-home')


class SearchPatients(LoginRequiredMixin, ListView):
    model = Patient
    template_name = 'users/patients_listview.html'
    context_object_name = 'patients'
    paginate_by = 10
    ordering = ['-date_added']

    def get_queryset(self):
        q = self.kwargs.get('q')
        if q is not None:
            try:
                int(q)
                qs = Patient.objects.filter(
                    Q(first_name__icontains=q) | Q(middle_name__icontains=q) | Q(last_name__icontains=q) | Q(
                        phone_number__icontains=q) | Q(uhid=q)
                )
            except ValueError:
                qs = Patient.objects.filter(
                    Q(first_name__icontains=q) | Q(middle_name__icontains=q) | Q(last_name__icontains=q) | Q(
                        phone_number__icontains=q)
                )
        else:
            qs = None
        return qs


class PatientUpdateView(SuccessMessageMixin, LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Patient
    template_name = 'users/users_update_patient.html'
    form_class = PatientRegistrationForm
    success_message = "Patient Details were successfully updated!"

    def form_valid(self, form):
        return super().form_valid(form)

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False


def patient_update_home(request):
    context = {
        'other_form': NewSessionStep1Form()
    }
    if request.method == 'POST':
        form = NewSessionStep1Form(request.POST)
        if form.is_valid():
            patient = form.cleaned_data['patient']
            return redirect('users:update_patient', patient.pk)
        context['other_form'] = form
    return render(request, 'bookings/bookings_home.html', context=context)


class PatientDetailView(LoginRequiredMixin, DetailView):
    model = Patient
    context_object_name = 'patient'


class PatientAutocompleteView(autocomplete.Select2QuerySetView):

    def get_queryset(self):
        qs = []
        if not self.request.user.is_authenticated:
            return Patient.objects.none()
        if self.q:
            qs = Patient.objects.filter(
                Q(first_name__icontains=self.q)| Q(middle_name__icontains=self.q) | Q(last_name__icontains=self.q) | Q(phone_number__icontains=self.q)
            )
        return qs


@login_required
def reports_home(request):
    context = {
        'title': 'Reports'
    }
    return render(request, 'reports/reports_home.html', context)


@login_required
def patient_listing_report(request):
    context = {
        'title': 'Patients Listing',
        'heading': 'Patients Listing',
        'filter_form': PatientReportFilterForm(request.POST or None),
        'reportTable': True,
        'patients': patient_list_root()[:50]
    }
    if request.method == 'POST':
        form = PatientReportFilterForm(request.POST)
        if form.is_valid():
            context['patients'] = patient_list_root(form.cleaned_data)

    return render(request, 'reports/reports_home.html', context)


@login_required
def booking_listing_report(request):
    context = {
        'title': 'Bookings Listing',
        'heading': 'Bookings listing',
        'filter_form': BookingReportFilter(request.POST or None),
        'reportTable': True,
        'sessions': bookings_list_root()[:50]
    }
    if request.method == 'POST':
        form = BookingReportFilter(request.POST)
        if form.is_valid():
            context['sessions'] = bookings_list_root(form.cleaned_data)

    return render(request, 'reports/reports_home.html', context)


@login_required
def payment_listing_report(request):
    context = {
        'title': 'Payment Listing',
        'heading': 'Payment listing',
        'filter_form': PaymentReportFilter(request.POST or None),
        'reportTable': True,
        'payments': payment_list_root()[:50]
    }
    if request.method == 'POST':
        form = PaymentReportFilter(request.POST)
        if form.is_valid():
            context['payments'] = payment_list_root(form.cleaned_data)

    return render(request, 'reports/reports_home.html', context)

users/templates/users/login.html
{% extends "users/logs_base.html" %}l>
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}
    {{ form|crispy }}
     <div class="submit-row">
         <input type="submit" value="Log in">&nbsp;
         <small>
            <a href="{% url 'password_reset' %}">Forgot Password?</a>
        </small>
     </div>
{% endblock %}

users/templates/users/logout.html
{% extends "users/logs_base.html" %}l>
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}
    <p>You have been successfully logged out!</p>
        <div class="submit-row">
            <label>&nbsp;</label><a href="{% url 'login' %}"><span class="btn button">Log me in!</span></a>
        </div>
    </p>
{% endblock %}

users/templates/users/logs_base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load crispy_forms_tags %}

<html lang="en-us" >
<head>
    {% if title %}
        <title>{{ title }} | ADT Booking System</title>
    {% else %}
        <title>ADT Booking System</title>
    {% endif %}
    <link rel="stylesheet" href="{% static 'bootstrap bundle/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/main.css' %}">





    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">


<meta name="robots" content="NONE,NOARCHIVE">
</head>


<body class=" login" id="bg" style="background-image: url('{% static "users/logo_and_icons/TNH_logo (copy).png"%}')";
  data-admin-utc-offset="10800">

<!-- Container -->
<div id="container">


    <!-- Header -->
    <div id="header">
        <div id="branding">
            <h1 id="site-name">
                {% if title %}
                    {{ title }}
                 {% else %}
                    ADT Booking
                {% endif %}
            </h1>
        </div>
    </div>
    <!-- END Header -->


    <!-- Content -->
    <div id="content" class="colM">

        <div id="content-main">

        <!--Pop up messages-->
            {% if msgs %}
                {% for tag, messages in msgs.items %}
                   {% for message in messages %}
                       <div class="alert alert-{{ tag }}">{{ message }}</div>
                   {% endfor %}
                {% endfor %}
            {% endif %}
        <!--end of popup messages-->


            <form method="POST" id="login-form" class="mx-auto p-3">
                {% csrf_token %}
                    {% block content %}

                    {% endblock %}
            </form>
        </div>
        <br class="clear">
    </div>
    <!-- END Content -->
<!-- END Container -->

</body>
</html>

users/templates/users/password_reset.html
{% extends "users/logs_base.html" %}l>
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}
    {{ form|crispy }}
     <div class="submit-row">
         <input type="submit" value="Request Reset">
     </div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "users/logs_base.html" %}l>
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}
    {{ form|crispy }}
     <div class="alert alert-success">
     Your password has been successfully reset!
     </div>
    <div class="btn btn-outline-warning"><a href="{% url 'login' %}">Log In</a> </div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "users/logs_base.html" %}l>
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}
    {{ form|crispy }}
     <div class="submit-row">
         <input type="submit" value="Log in">&nbsp;
         <small>
            <a href="{% url 'password_reset' %}">Reset Password</a>
        </small>
     </div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "users/logs_base.html" %}l>
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="alert alert-info">
        An email has been sent to you with instructions to reset your password
    </div>
{% endblock %}

users/templates/users/patient_detail.html
{% extends 'bookings/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
    <div class="card align-items-center p-2 mx-auto">
        <div class="card-header text-center bg-unset">
            <h3 id="header2" class="header2-fallback-color">
                {{ patient.full_name.title }}({{ patient.age }}yrs)
            </h3>
        </div>
        <div class="card-body">
            <table class="table text-center">
                <thead class="bg-theme">
                    <tr>
                        <th scope="rowgroup" class="font-weight-bold" colspan="3">
                            <h4>Patient Info</h4>
                        </th>
                    </tr>
                </thead>
                <tbody class="text-left">
                <tr>
                    <td>
                        <b>Gender: </b> {{ patient.gender }}
                    </td>
                    <td>
                        <b>Date of Birth: </b>{{ patient.date_of_birth }}
                    </td>
                    <td>
                        <b>UHID: </b>{% if patient.uhid %} {{ patient.uhid }}{% else %} -- {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>Phone Number: </b>{{ patient.phone_number }}
                    </td>
                    <td></td>
                    <td><b>Email: </b>{% if patient.email %} {{ patient.email }}{% else %} -- {% endif %}</td>
                </tr>
                <tr>
                </tr>
                <tr>
                    <th scope="rowgroup" class="bg-faded-theme text-center" colspan="3" >
                        <h4>Current Bookings</h4>
                    </th>
                </tr>
                <tr>
                    <td><b>Admission - Discharge(Dates)</b></td>
                    <td><b>Service</b></td>
                    <td><b>Location</b></td>
                </tr>
                {% for session in patient.session_set.all|dictsortreversed:"start_date" %}
                    {% if not session.is_past %}
                    <tr>
                        <td class="attention-seeking-link">
                            <a href="{% url 'bookings:session-detail' session.pk %}">{{ session.start_date }} - {{ session.end_date }}</a>
                        </td>
                        <td><b>{{ session.service }}</b></td>
                        <td><b>{{ session.location }}</b></td>
                    </tr>
                    {% endif %}
                {% endfor %}
                <tr>
                    <th scope="rowgroup" class="bg-theme text-center" colspan="3" >
                        <h4>Past Bookings(Discharged)</h4>
                    </th>
                </tr>
                <tr>
                    <td><b>Admission - Disharge(Dates)</b></td>
                    <td><b>Service</b></td>
                    <td><b>Location</b></td>
                </tr>
                {% for session in patient.session_set.all|dictsortreversed:"start_date" %}
                    {% if session.is_past %}
                    <tr>
                        <td class="attention-seeking-link">
                            <a href="{% url 'bookings:session-detail' session.pk %}">{{ session.start_date }} - {{ session.end_date }}</a>
                        </td>
                        <td><b>{{ session.service }}</b></td>
                        <td><b>{{ session.location }}</b></td>
                    </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div>
            <span class="button btn">
                <a href="{% url 'users:view_patients' %}">Back</a>
            </span>
            {% if user.is_staff %}
                <span class="btn btn-outline-secondary">
                    <a href="{% url 'users:update_patient' object.id %}">Edit</a>
                </span>
            {% endif %}
        </div>
    </div>
{% endblock %}

users/templates/users/patients_listview.html
{% extends 'bookings/base.html' %}
{% block content %}
    <h1 id="header2">Patients Listing</h1>


    {% if patients %}

        <table class="table table-hover table-striped">

            <thead class="float-md-none">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Phone/Tel No.</th>
                    <th scope="col">Email</th>
                    <th scope="col">UHID</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Date of Birth</th>
                    <th scope="col">Age(yrs)</th>
                    <th scope="col">Registered on</th>
                    <th scope="col">Last Modified</th>
                </tr>
            </thead>

            <tbody>

                {% for patient in patients %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'users:patient-detail' patient.pk %}">{{ patient.full_name.title }}</a> </td>
                        <td>{% if patient.phone_number %}{{ patient.phone_number }}{% else %}--{% endif %}</td>
                        <td>{% if patient.email == None or patient.email == '' %}--{% else %}{{ patient.email }}{% endif %}</td>
                        <td>{% if patient.uhid %}{{ patient.uhid }}{% else %}--{% endif %}</td>
                        <td>{{ patient.gender.initial }}</td>
                        <td>{{ patient.date_of_birth }}</td>
                        <td>{{ patient.age }}</td>
                        <td>{{ patient.date_added|date:"jS-N-Y" }}</td>
                        <td>{{ patient.last_modified|date:"jS-N-Y H:i" }}</td>
                    </tr>
                {% endfor %}


            </tbody>
            <tfoot>
                <tr>
                    <td></td>
                    <td><small>{{ patients.count }} Records</small></td>
                    <td></td>
                    <td><small>Generated on: {% now "jS F Y H:i" %}</small></td>
                    <td></td>
                    <td><small>By: {{ user.username }}@adtbooking</small></td>
                    <td></td>
            </tfoot>
        </table>

             <!--Start of page navigation buttons-->

                <div class="btn-group mb-3" role="group" aria-label="Pages Navigation">
                    {% if is_paginated %}

                        {% if page_obj.has_previous %}
                            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                        {% endif %}

                        {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif %}

            {% endif %}
                </div>


                <!--End of page navigation buttons-->

    {% else %}


        <div class="card align-items-center p-2 mx-auto">
            <div class="card-body">
                <p class="alert alert-danger">No Patients registered or No search results found for the specified criteria</p>
                <p class="alert alert-info">Please adjust criteria or Register one</p>
            </div>
            <div class="card-footer">0 Records</div>
        </div>
    {% endif %}
{% endblock %}

users/templates/users/users_register_patient.html
{% extends "users/logs_base.html" %}
{% block content %}
    {% load static %}
    {% load crispy_forms_tags %}
    <h1 id="header2">Patient Registration</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="submit-row">
            <input class="btn button" type="submit" value="+ Add">
        </div>
        <div class="d-flex align-items-center">
            <small class="text-muted">Waiting...</small>
        <div class="spinner-grow spinner-border-sm text-secondary ml-auto" role="status" aria-hidden="true"></div>
        </div>
    </form>
{% endblock %}

users/templates/users/users_update_patient.html
{% extends "users/logs_base.html" %}
{% block content %}
    {% load static %}
    {% load crispy_forms_tags %}
    <h1 id="header2">Update info for {{ object }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="submit-row text-center">
            <a href="{% url 'users:patient_update_home'  %}"><span class="btn btn-outline-info">Cancel</span></a>
            <input class="btn button" type="submit" value="Update">
        </div>
        <div class="d-flex align-items-center">
            <small class="text-muted">Waiting...</small>
        <div class="spinner-grow spinner-border-sm text-secondary ml-auto" role="status" aria-hidden="true"></div>
        </div>
    </form>
{% endblock %}