ADT_booking/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users.views import register_patient
from bookings.views import redirect_to_home

urlpatterns = [
    path('', redirect_to_home, name='redirect-to-home'),
    path('adtbooking/', include('bookings.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('users/register-patient/', register_patient, name='register-patient'),
    path('users/', include('users.urls')),
    path('payment/', include('payments.urls'))
]


urlpatterns += staticfiles_urlpatterns()

admin.site.site_header = "ADT Booking Admin"
admin.site.site_title = "ADT Admin Site"
admin.site.index_title = "Welcome to ADT Booking System"

bookings/urls.py
from django.urls import path
from . import views

app_name = 'bookings'

urlpatterns = [
    path('session/view/all', views.SessionListView.as_view(), name='view_session_all'),
    path('session/new/1', views.CreateSessionStep1View.as_view(), name='new_session1'),
    path('session/new/2', views.CreateSessionStep2View.as_view(), name='new_session2'),
    path('session/new/3', views.CreateSessionStep3View.as_view(), name='new_session3'),
    path('session/new/claim-payment',
         views.CreateSessionClaimConservativePaymentView.as_view(),
         name='new_session_claim_conservative_payment'),
    path('session/new/3b', views.CreateSessionStep3bView.as_view(), name='new_session3b'),
    path('update-session-home/', views.session_update_home, name='session_update_home'),
    path('update-session/<int:pk>/', views.PatientSessionListView.as_view(), name='update_session'),
    path('session/<int:pk>/', views.SessionDetailView.as_view(), name='session-detail'),
    path('session/edit/<int:pk>/', views.SessionUpdate.as_view(), name='session-edit'),
    path('', views.home, name='bookings-home')
]

payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    path('view/all', views.PaymentsListView.as_view(), name='view_payment_all'),
    path('new/choose', views.choose_payment_to_post, name='choose_payment_to_post'),
    path('new/<str:choice>', views.create_payment, name='create_payment'),
    path('update-payment-home/', views.payment_update_home, name='payment_update_home'),
    path('update-payment/<int:pk>/', views.PatientPaymentListView.as_view(), name='update_payment'),
    path('payment/edit/<int:pk>/', views.PaymentUpdateView.as_view(), name='payment-edit'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('view-patients/', views.PatientsListView.as_view(), name='view_patients'),
    path('update-patient-home/', views.patient_update_home, name='patient_update_home'),
    path('update-patient/<int:pk>/', views.PatientUpdateView.as_view(), name='update_patient'),
    path('search-patient/home/', views.search_patient_home, name='search_patient_home'),
    path('search-patient/<str:q>/', views.SearchPatients.as_view(), name='search_patient'),
    path('patient-autocomplete', views.PatientAutocompleteView.as_view(), name='patient_autocomplete'),
    path('patient/<int:pk>', views.PatientDetailView.as_view(), name='patient-detail'),
    path('reports/home', views.reports_home, name='reports_home'),
    path('reports/bookings/list', views.booking_listing_report, name='booking_listing_report'),
    path('reports/patients/list', views.patient_listing_report, name='patient_listing_report'),
    path('reports/payments/list', views.payment_listing_report, name='payment_listing_report')
]

users/models.py
from django.db import models
from simple_history.models import HistoricalRecords
from django.conf import settings
from django.utils import timezone
from django.urls import reverse

# Create your models here.

DEFAULT_EMAIL = 'none@none.none'


class Gender(models.Model):
    name = models.CharField(max_length=10, unique=True, editable=False)
    history = HistoricalRecords()

    def __str__(self):
        return self.name

    @property
    def initial(self):
        if self.name == 'Other*':
            return '*'
        return self.name[0].upper()


class Patient(models.Model):
    first_name = models.CharField(max_length=20)
    middle_name = models.CharField(max_length=20, blank=True)
    last_name = models.CharField(max_length=20)
    date_of_birth = models.DateField()
    phone_number = models.CharField(max_length=12, unique=True)
    gender = models.ForeignKey(Gender, on_delete=models.PROTECT, default=3)
    email = models.EmailField(unique=True, null=True, blank=True)
    uhid = models.BigIntegerField(unique=True, blank=True, null=True)
    history = HistoricalRecords()
    date_added = models.DateField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('users:patient-detail', kwargs={'pk': self.pk})

    @property
    def full_name(self):
        if self.middle_name:
            return f'{self.first_name} {self.middle_name} {self.last_name}'
        return f'{self.first_name} {self.last_name}'

    @property
    def age(self):
        today = timezone.now().date()
        age = today.year - self.date_of_birth.year - (
                (today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day)
        )

        return age

    def __str__(self):
        return self.full_name


class Doctor(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=12)
    gender = models.ForeignKey(Gender, on_delete=models.PROTECT)
    email = models.EmailField(default=DEFAULT_EMAIL, null=True)
    history = HistoricalRecords()
    date_added = models.DateField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

users/views.py
# Other imports
from django.db.models import Q
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# end of other imports


# mixins and generic views class imports
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import (
    ListView,
    UpdateView,
    DetailView
)
from bookings.forms import NewSessionStep1Form
# end of generic views and mixins imports

# dal auto-complete imports
from dal import autocomplete
# end of dal auto-complete

# models import
from .models import Patient
# end of model imports

# form imports
from .forms import (
    PatientRegistrationForm,
    PatientReportFilterForm,
    BookingReportFilter,
    PaymentReportFilter
)

# end of form imports

"""end of forms imports"""

from users.models import Patient
from .filters import(
    patient_list_root,
    bookings_list_root,
    payment_list_root
)

# Create your views here.
@login_required
def register_patient(request):
    context = {
        'title': 'New Patient'
    }
    if request.method == 'POST':
        form = PatientRegistrationForm(request.POST)
        context['form'] = form
        if form.is_valid():
            form.save()
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            messages.success(request, f"The patient '{first_name} {last_name}' has been successfully registered")
            success = [f"The patient '{first_name} {last_name}' has been successfully registered", ]

            # pop-up (messages and context)

            msgs = {}
            error = []
            warning = []
            msgs['success'] = [msg for msg in success]
            msgs['danger'] = [msg for msg in error]
            msgs['warning'] = [msg for msg in warning]
            context['msgs'] = msgs
            context['title'] = 'Success! close pop-up'

            # end of pop-up (messages and context)

            return render(request, template_name='users/logs_base.html', context=context)
    else:
        form = PatientRegistrationForm()
        context['form'] = form
    return render(request, 'users/users_register_patient.html', context)


class PatientsListView(LoginRequiredMixin, ListView):
    model = Patient
    template_name = 'users/patients_listview.html'
    context_object_name = 'patients'
    paginate_by = 20
    ordering = ['-last_modified']


def search_patient_home(request):
    if request.method == 'GET':
        q = (request.GET.get('q', None))
        if q == '':
            return redirect('bookings:bookings-home')
        return redirect('users:search_patient', q)
    return redirect('bookings:bookings-home')


class SearchPatients(LoginRequiredMixin, ListView):
    model = Patient
    template_name = 'users/patients_listview.html'
    context_object_name = 'patients'
    paginate_by = 10
    ordering = ['-date_added']

    def get_queryset(self):
        q = self.kwargs.get('q')
        if q is not None:
            try:
                int(q)
                qs = Patient.objects.filter(
                    Q(first_name__icontains=q) | Q(middle_name__icontains=q) | Q(last_name__icontains=q) | Q(
                        phone_number__icontains=q) | Q(uhid=q)
                )
            except ValueError:
                qs = Patient.objects.filter(
                    Q(first_name__icontains=q) | Q(middle_name__icontains=q) | Q(last_name__icontains=q) | Q(
                        phone_number__icontains=q)
                )
        else:
            qs = None
        return qs


class PatientUpdateView(SuccessMessageMixin, LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Patient
    template_name = 'users/users_update_patient.html'
    form_class = PatientRegistrationForm
    success_message = "Patient Details were successfully updated!"

    def form_valid(self, form):
        return super().form_valid(form)

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False


def patient_update_home(request):
    context = {
        'other_form': NewSessionStep1Form()
    }
    if request.method == 'POST':
        form = NewSessionStep1Form(request.POST)
        if form.is_valid():
            patient = form.cleaned_data['patient']
            return redirect('users:update_patient', patient.pk)
        context['other_form'] = form
    return render(request, 'bookings/bookings_home.html', context=context)


class PatientDetailView(LoginRequiredMixin, DetailView):
    model = Patient
    context_object_name = 'patient'


class PatientAutocompleteView(autocomplete.Select2QuerySetView):

    def get_queryset(self):
        qs = []
        if not self.request.user.is_authenticated:
            return Patient.objects.none()
        if self.q:
            qs = Patient.objects.filter(
                Q(first_name__icontains=self.q)| Q(middle_name__icontains=self.q) | Q(last_name__icontains=self.q) | Q(phone_number__icontains=self.q)
            )
        return qs


@login_required
def reports_home(request):
    context = {
        'title': 'Reports'
    }
    return render(request, 'reports/reports_home.html', context)


@login_required
def patient_listing_report(request):
    context = {
        'title': 'Patients Listing',
        'heading': 'Patients Listing',
        'filter_form': PatientReportFilterForm(request.POST or None),
        'reportTable': True,
        'patients': patient_list_root()[:50]
    }
    if request.method == 'POST':
        form = PatientReportFilterForm(request.POST)
        if form.is_valid():
            context['patients'] = patient_list_root(form.cleaned_data)

    return render(request, 'reports/reports_home.html', context)


@login_required
def booking_listing_report(request):
    context = {
        'title': 'Bookings Listing',
        'heading': 'Bookings listing',
        'filter_form': BookingReportFilter(request.POST or None),
        'reportTable': True,
        'sessions': bookings_list_root()[:50]
    }
    if request.method == 'POST':
        form = BookingReportFilter(request.POST)
        if form.is_valid():
            context['sessions'] = bookings_list_root(form.cleaned_data)

    return render(request, 'reports/reports_home.html', context)


@login_required
def payment_listing_report(request):
    context = {
        'title': 'Payment Listing',
        'heading': 'Payment listing',
        'filter_form': PaymentReportFilter(request.POST or None),
        'reportTable': True,
        'payments': payment_list_root()[:50]
    }
    if request.method == 'POST':
        form = PaymentReportFilter(request.POST)
        if form.is_valid():
            context['payments'] = payment_list_root(form.cleaned_data)

    return render(request, 'reports/reports_home.html', context)

users/templates/reports/reports_home.html
{% extends 'bookings/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}
{% block content %}
    <script type="text/javascript" src="{% static "bootstrap bundle/FileSaver.min.js" %}"></script>
    <script type="text/javascript" src="{% static "bootstrap bundle/xlsx.core.min.js" %}"></script>
    <script type="text/javascript" src="{% static "bootstrap bundle/tableexport.js" %}"></script>
    <h1 id="header2">{% if heading %}{{ heading }}{% else %}Reports{% endif %}</h1>
    {% if filter_form and reportTable %}

        {% if filter_form %}
            <div class="card mx-auto">
                <div class="card-header unset-bg" id="filterHeading">
                    <h5 class="mb-0">
                        <button class="btn btn-link collapsed"
                                data-toggle="collapse"
                                data-target="#filter-form" aria-expanded="false"
                                aria-controls="filter-form">
                            Filter Report <small class="text-muted">(show/hide this form)</small>
                        </button>
                    </h5>
                </div>
                <form class="main-form2 p-2 m-1 mx-auto text-center collapse show"
                      id="filter-form" aria-labelledby="filterHeading"
                      method="post" aria-expanded="false">
                    {% csrf_token %}
                    {% crispy filter_form %}
                </form>
            </div>
        {% endif %}

        {% if reportTable %}
            <table class="table table-bordered" id="reportTable">
                {% if patients %}
                    <thead class="float-md-none">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Phone/Tel No.</th>
                    <th scope="col">Email</th>
                    <th scope="col">UHID</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Date of Birth</th>
                    <th scope="col">Age(yrs)</th>
                    <th scope="col">Registered on</th>
                    <th scope="col">Last Modified</th>
                </tr>
            </thead>

            <tbody>

                {% for patient in patients %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'users:patient-detail' patient.pk %}">{{ patient.full_name.title }}</a> </td>
                        <td>{% if patient.phone_number %}{{ patient.phone_number }}{% else %}--{% endif %}</td>
                        <td>{% if patient.email == None or patient.email == '' %}--{% else %}{{ patient.email }}{% endif %}</td>
                        <td>{% if patient.uhid %}{{ patient.uhid }}{% else %}--{% endif %}</td>
                        <td>{{ patient.gender.initial }}</td>
                        <td>{{ patient.date_of_birth }}</td>
                        <td>{{ patient.age }}</td>
                        <td>{{ patient.date_added|date:"jS-N-Y" }}</td>
                        <td>{{ patient.last_modified|date:"jS-N-Y" }}</td>
                    </tr>
                {% endfor %}


            </tbody>
            <tfoot>
                <tr>
                    <td></td>
                    <td><small>{{ patients.count }} Records</small></td>
                    <td></td>
                    <td><small>Generated on: {% now "jS F Y H:i" %}</small></td>
                    <td></td>
                    <td><small>By: {{ user.username }}@adtbooking</small></td>
                    <td></td>
            </tfoot>
                {% endif %}

                {% if sessions %}
                    <thead class="float-md-none">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Patient Name</th>
                    <th scope="col">Service</th>
                    <th scope="col">Location</th>
                    <th scope="col">Doctor's Name</th>
                    <th scope="col">Admission Date</th>
                    <th scope="col">Discharge Date</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>

            <tbody>

                {% for session in sessions %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'bookings:session-detail' session.id %}">
                                {{ session.patient }}
                            </a>
                            {% if session.timeline == 'PAST' %}
                                <span style="color: #6fc6de;" class="font-weight-bolder">&#10004</span>
                             {% elif session.timeline == 'ACTIVE' %}
                                <span style="color: #dadada" class="font-weight-bolder">&check;</span>
                            {% elif session.timeline == 'INCONSISTENT' %}
                               <span style="color: #de0b00;" class="font-weight-bolder"> &#10008;</span>
                            {% else %}
                                <span style="color: #468012;" class="font-weight-bolder">&#10171;</span>
                            {% endif %}
                        </td>
                        <td>{{ session.service }}</td>
                        <td>{{ session.location }}</td>
                        <td>{{ session.doctor }}</td>
                        <td>{{ session.start_date|date:"jS-N-Y"}}</td>
                        <td>{{ session.end_date|date:"jS-N-Y"}}</td>
                        <td>
                            <span style="background-color: {{ session.status.indicator }}; color: whitesmoke;" class="text-center p-1 rounded">
                                <i>{{ session.status }}</i>
                            </span>
                        </td>
                    </tr>
                {% endfor %}


            </tbody>
            <tfoot>
                <tr>
                    <td></td>
                    <td colspan="3"><small>{{ sessions.count }}{% if not sessions.count %}{{ sessions|length }}{% endif %} Records</small></td>
                    <td colspan="2"><small>Generated on: {% now "jS F Y H:i" %}</small></td>
                    <td colspan="2"><small>By: {{ user.username }}@adtbooking</small></td>
            </tfoot>
                {% endif %}

                {% if payments %}
                    <thead class="float-md-none">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Paid By</th>
                    <th scope="col">Payment Type</th>
                    <th scope="col">Extra Tags</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Date of payment</th>
                    <th scope="col">Last Edited by</th>
                </tr>
            </thead>

            <tbody>

                {% for payment in payments %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            {% if user.is_staff %}<a href="{% url 'payments:payment-edit' payment.pk %}">{{ payment.patient }}</a>
                            {% else %}{{ payment.patient }}{% endif %}
                        </td>
                        <td>{{ payment.get_real_instance.type }}</td>
                        <td>{{ payment.get_real_instance.additional_info }}</td>
                        <td>{{ payment.denom}} {{ payment.amount|intcomma }}{{ payment.denom_closer }}</td>
                        <td>{{ payment.date|date:"jS-N-Y" }}</td>
                        <td>{{ payment.history.first.history_user }}</td>
                    </tr>
                {% endfor %}


            </tbody>
            <tfoot>
                <tr>
                    <td><small>{{ payments.count }}{% if not payments.count %}{{ payments|length }}{% endif %} Records</small></td>
                    <td><small>Generated on: {% now "jS F Y H:i" %}</small></td>
                    <td><small>By: {{ user.username }}@adtbooking</small></td>
            </tfoot>
                {% endif %}

            </table>
        {% endif %}

    {% else %}
        <div id="accordion" class="mx-auto text-center m-5">
  <div class="card">
    <div class="card-header unset-bg" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          PATIENTS
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
        <a href="{% url 'users:patient_listing_report' %}">
            <div class="btn btn-link m-2">Patients' List</div>
        </a> <br>
        <div class="btn btn-link m-2">User  Logs</div>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header unset-bg" id="headingTwo">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          BOOKINGS
        </button>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
      <div class="card-body">
        <a href="{% url 'users:booking_listing_report' %}">
            <div class="btn btn-link m-2">Bookings List</div><br>
        </a>
        <div class="btn btn-link m-2">User  Logs</div>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header unset-bg" id="headingThree">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          PAYMENTS
        </button>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
      <div class="card-body">
        <a href="{% url 'users:payment_listing_report' %}">
            <div class="btn btn-link m-2">Payments List</div>
        </a> <br>
        <div class="btn btn-link m-2">User  Logs</div>
      </div>
    </div>
  </div>
</div>
    {% endif %}
{% endblock %}